name: circular_menu
description:  A simple animated circular menu for Flutter, Adjustable radius, colors, alignment, animation curve and animation duration.
version: 2.0.1
author: Hasan Mohammed <hasanmohammed.hm1@gmail.com>
homepage: https://github.com/hasan-hm1/circular_menu

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

